spring:
  application:
    name: spring-security-and-validation
  datasource:
    url: jdbc:mysql://localhost/enterprise-architecture
    username: root
    password: T0kh@66053
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximumPoolSize: 10
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2008Dialect
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log
server:
  port: 80
